name: ci-tests

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name:
          - "linting"
          - "ubuntu-py37"
          - "ubuntu-py310"
          - "windows-py38"

        include:
          - name: "linting"
            python: "3.8"
            os: ubuntu-latest
            tox_env: "lint"
          - name: "ubuntu-py37"
            python: "3.7"
            os: "ubuntu-latest"
            tox_env: "py37"
          - name: "ubuntu-py310"
            python: "3.10"
            os: "ubuntu-latest"
            tox_env: "py310"
          - name: "windows-py38"
            python: "3.8"
            os: windows-latest
            tox_env: "py38"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install tox virtualenv
      - name: Test build
        run: "tox -e ${{ matrix.tox_env }}"
